refactor job manager
CJSCommonPlatform/job-manager pull request #3
Opened 2018-07-27 15:47 UTC by benouaer

2018-08-02 11:27 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/FillCakeTinTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
final

2018-08-02 11:27 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/GetIngredientsTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
final

2018-08-02 11:28 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/GetUtensilsTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
final

2018-08-02 11:29 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/JobUtil.java
> +        return ExecutionInfo.executionInfo().from(lastJob)
static import?

2018-08-02 11:29 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/JobUtil.java
> +        return ExecutionInfo.executionInfo()
static import?

2018-08-02 11:29 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/MixIngredientsTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
final

2018-08-02 11:30 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/SliceAndEatCakeTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
final

2018-08-02 11:30 UTC, allanmckenzie commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/SwitchOvenOnTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
final

2018-08-02 11:37 UTC, allanmckenzie commented on job-executor/src/test/java/uk/gov/moj/cpp/task/execution/JobSchedulerTest.java
> +        ArgumentCaptor<TimerConfig> timerConfigArgumentCaptor = ArgumentCaptor.forClass(TimerConfig.class);
Can use the @Captor annotation if you want to make this less noisy

2018-08-02 11:38 UTC, allanmckenzie commented on job-manager-it/pom.xml
> +            <version>1.2</version>
Shouldn't need version here

2018-08-02 11:39 UTC, allanmckenzie commented on job-manager-it/pom.xml
> +            <artifactId>test-utils-core</artifactId>
Should use the property for the version here (like below)

2018-08-02 11:40 UTC, allanmckenzie commented on job-manager-it/src/main/java/uk/gov/moj/cpp/jobmanager/it/util/OpenEjbJobJdbcRepository.java
> +                jobsCount = rs.getInt(1);
If you return rs.getInt(1) here you won't need the jobCount variable

2018-08-02 11:41 UTC, allanmckenzie commented on job-manager-it/src/main/java/uk/gov/moj/cpp/jobmanager/it/util/OpenEjbJobJdbcRepository.java
> +        while (i < count) {
Should be a for loop

2018-08-02 11:42 UTC, allanmckenzie commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +        Thread.sleep(3000);
Maybe use the Poller here rather than using Thread.sleep()

2018-08-02 11:42 UTC, allanmckenzie commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +                System.out.println(workerThreadName);
Remove System.out

2018-08-02 11:44 UTC, allanmckenzie commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +                    e.printStackTrace();
remove printStackTrace() and don't catch the exceptions the the test method throw Exception instead

2018-08-02 11:45 UTC, allanmckenzie commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +            ex.printStackTrace();
don't catch the Exception

2018-08-02 11:46 UTC, allanmckenzie approved these changes

2018-08-02 12:16 UTC, mapingo requested changes

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/BakeryService.java
> +        final ExecutionInfo startCakeJobRequest = new ExecutionInfo(objectConverter.convert(firstTask.getTaskData()), firstTask.toString(), now(), ExecutionStatus.STARTED);
startCakeJobRequest does not seem to be the correct name anymore

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/BakeCakeTask.java
> +import static java.time.LocalDateTime.now;
looks like the wrong code style template is being used...statics should be first

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/GetIngredientsTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
"job" argument needs renaming, and there is no final

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/FillCakeTinTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
"job" argument needs renaming, and there is no final

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/BakeCakeTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
"job" argument needs renaming, and there is no final

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/GetUtensilsTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
"job" argument needs renaming, and there is no final

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/MixIngredientsTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
"job" argument needs renaming, and there is no final

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/SliceAndEatCakeTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
"job" argument needs renaming, and there is no final

2018-08-02 12:16 UTC, mapingo commented on example/src/main/java/uk/gov/moj/cpp/jobmanager/example/task/SwitchOvenOnTask.java
> +    public ExecutionInfo execute(ExecutionInfo job) {
"job" argument needs renaming, and there is no final

2018-08-02 12:16 UTC, mapingo commented on example/src/test/java/uk/gov/moj/cpp/jobmanager/example/BakeryServiceIT.java
> +    private uk.gov.moj.cpp.jobmanager.it.util.OpenEjbJobJdbcRepository repository;
does this need to be fully qualified?

2018-08-02 12:16 UTC, mapingo commented on job-executor/src/main/java/uk/gov/moj/cpp/task/execution/JobScheduler.java
> +    private Logger logger;
injection should be package private

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/pom.xml
> +            <version>1.17.2</version>
version should be defined as a property in the base pom

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/pom.xml
> +            <version>1.2</version>
version should be defined as a property in the base pom

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/pom.xml
> +            <version>1.17.2</version>
version should be defined as a property in the base pom

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/pom.xml
> +            <version>4.1.2</version>
version should be defined as a property in the base pom

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/src/main/java/uk/gov/moj/cpp/jobmanager/it/util/OpenEjbJobJdbcRepository.java
> +        try (Connection connection = dataSource.getConnection()) {
final?

2018-08-02 12:16 UTC, mapingo commented on pom.xml
> +                <version>1.17.2</version>
version should be defined as a property

2018-08-02 12:16 UTC, mapingo commented on jobstore-persistence/src/test/java/uk/gov/moj/cpp/jobstore/persistence/JobTest.java
> +        Job originalJob = new Job(randomUUID(), jobData, NEXT_TASK, nextTaskStartTime, empty(), empty());
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-persistence/src/test/java/uk/gov/moj/cpp/jobstore/persistence/JobTest.java
> +        Job copiedExecutionInfo = Job.job().from(originalJob).build();
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-persistence/src/main/java/uk/gov/moj/cpp/jobstore/persistence/JobJdbcRepository.java
> +    protected Logger logger;
should package protected

2018-08-02 12:16 UTC, mapingo commented on jobstore-persistence/src/main/java/uk/gov/moj/cpp/jobstore/persistence/JobJdbcRepository.java
> +    protected JdbcRepositoryHelper jdbcRepositoryHelper;
package protected as above

2018-08-02 12:16 UTC, mapingo commented on jobstore-persistence/pom.xml
> +            <version>1.7.22</version>
version should be defined in the base pom

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/test/java/uk/gov/moj/cpp/jobstore/api/task/ExecutionInfoTest.java
> +        Job job = new Job(randomUUID(), jobData, NEXT_TASK, nextTaskStartTime, empty(), empty());
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/test/java/uk/gov/moj/cpp/jobstore/api/task/ExecutionInfoTest.java
> +        ExecutionInfo copiedExecutionInfo = ExecutionInfo.executionInfo().fromJob(job).build();
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/test/java/uk/gov/moj/cpp/jobstore/api/task/ExecutionInfoTest.java
> +        ExecutionInfo copiedExecutionInfo = ExecutionInfo.executionInfo().withJobData(jobData).build();
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/test/java/uk/gov/moj/cpp/jobstore/api/task/ExecutionInfoTest.java
> +        ExecutionInfo copiedExecutionInfo = ExecutionInfo.executionInfo().withNextTaskStartTime(nextTaskStartTime).build();
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/test/java/uk/gov/moj/cpp/jobstore/api/task/ExecutionInfoTest.java
> +        ExecutionInfo copiedExecutionInfo = ExecutionInfo.executionInfo().withExecutionStatus(ExecutionStatus.STARTED).build();
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/test/java/uk/gov/moj/cpp/jobstore/api/task/ExecutionInfoTest.java
> +        ExecutionInfo originalExecutionInfo = new ExecutionInfo(jobData,
final?

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/main/java/uk/gov/moj/cpp/jobstore/api/task/ExecutionStatus.java
> +    STARTED, INPROGRESS, COMPLETED;
"INPROGRESS"  could be "IN_PROGRESS"

2018-08-02 12:16 UTC, mapingo commented on jobstore-api/src/main/java/uk/gov/moj/cpp/jobstore/api/task/ExecutableTask.java
>       * @return A Job containing the result of the processing and possible further data
should be ExecutionInfo now

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +                String workerThreadName = new StringBuilder("T").append(count).append(" Worker: ").toString();
final

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +                Stream<Job> jobStream = jobService.getUnassignedJobsFor(workerId);
final

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +        Liquibase eventStoreLiquibase = new Liquibase(LIQUIBASE_JOB_STORE_DB_CHANGELOG_XML,
final

2018-08-02 12:16 UTC, mapingo commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobSchedulerIT.java
> +        Liquibase eventStoreLiquibase = new Liquibase(LIQUIBASE_JOB_STORE_DB_CHANGELOG_XML,
final

2018-08-02 15:31 UTC, benouaer commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +                String workerThreadName = new StringBuilder("T").append(count).append(" Worker: ").toString();
removed the variable

2018-08-02 15:31 UTC, benouaer commented on job-manager-it/src/test/java/uk/gov/moj/cpp/jobmanager/it/JobServiceIT.java
> +                Stream<Job> jobStream = jobService.getUnassignedJobsFor(workerId);
removed the variable

2018-08-03 08:33 UTC, mapingo approved these changes

2018-08-03 09:11 UTC, merged